// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq2fOpEavWfevtoTSg5jq01usFrj-2syI',
    appId: '1:861666413246:web:63b79304047663e9946cef',
    messagingSenderId: '861666413246',
    projectId: 'nooneleftbehind-ed8b4',
    authDomain: 'nooneleftbehind-ed8b4.firebaseapp.com',
    databaseURL: 'https://nooneleftbehind-ed8b4-default-rtdb.firebaseio.com',
    storageBucket: 'nooneleftbehind-ed8b4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi3p-edwYdN8FsQ-kvR2O9pgE1dCkHsDs',
    appId: '1:861666413246:android:63fd3181b398a737946cef',
    messagingSenderId: '861666413246',
    projectId: 'nooneleftbehind-ed8b4',
    databaseURL: 'https://nooneleftbehind-ed8b4-default-rtdb.firebaseio.com',
    storageBucket: 'nooneleftbehind-ed8b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7g1PxKEV18w8NF30bYCzifKP9PP7q4hk',
    appId: '1:861666413246:ios:c0abf21385a5c681946cef',
    messagingSenderId: '861666413246',
    projectId: 'nooneleftbehind-ed8b4',
    databaseURL: 'https://nooneleftbehind-ed8b4-default-rtdb.firebaseio.com',
    storageBucket: 'nooneleftbehind-ed8b4.firebasestorage.app',
    iosBundleId: 'com.example.noOneLeftBehind',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7g1PxKEV18w8NF30bYCzifKP9PP7q4hk',
    appId: '1:861666413246:ios:c0abf21385a5c681946cef',
    messagingSenderId: '861666413246',
    projectId: 'nooneleftbehind-ed8b4',
    databaseURL: 'https://nooneleftbehind-ed8b4-default-rtdb.firebaseio.com',
    storageBucket: 'nooneleftbehind-ed8b4.firebasestorage.app',
    iosBundleId: 'com.example.noOneLeftBehind',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAq2fOpEavWfevtoTSg5jq01usFrj-2syI',
    appId: '1:861666413246:web:fa461003323738ea946cef',
    messagingSenderId: '861666413246',
    projectId: 'nooneleftbehind-ed8b4',
    authDomain: 'nooneleftbehind-ed8b4.firebaseapp.com',
    databaseURL: 'https://nooneleftbehind-ed8b4-default-rtdb.firebaseio.com',
    storageBucket: 'nooneleftbehind-ed8b4.firebasestorage.app',
  );
}